### ISSUE TITLE
Some helpful links for using git

### ISSUE THREAD

**Issue by nandhact** [gazlaws-dev/CompilerLab#2]
https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

https://product.hubspot.com/blog/git-and-github-tutorial-for-beginners

http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by gazlaws-dev** [comment]
//for first time use - fork
git clone https://github.com/gazlaws-dev/CompilerLab.git
//to be in sync
git pull upstream master

//to make changes
<git checkout -b feature/stagex>
//make changes now
git add stagex
git commit -m "message"

git push origin feature/stagex
or
git push origin master
